name: clean_architecture_study
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true