const githubResult = """
{
  "total_count": 156,
  "incomplete_results": false,
  "items": [
    {
      "login": "jadiel",
      "id": 76293,
      "node_id": "MDQ6VXNlcjc2Mjkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/76293?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadiel",
      "html_url": "https://github.com/jadiel",
      "followers_url": "https://api.github.com/users/jadiel/followers",
      "following_url": "https://api.github.com/users/jadiel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadiel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadiel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadiel/subscriptions",
      "organizations_url": "https://api.github.com/users/jadiel/orgs",
      "repos_url": "https://api.github.com/users/jadiel/repos",
      "events_url": "https://api.github.com/users/jadiel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadiel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielam",
      "id": 1026067,
      "node_id": "MDQ6VXNlcjEwMjYwNjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1026067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielam",
      "html_url": "https://github.com/jadielam",
      "followers_url": "https://api.github.com/users/jadielam/followers",
      "following_url": "https://api.github.com/users/jadielam/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielam/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielam/orgs",
      "repos_url": "https://api.github.com/users/jadielam/repos",
      "events_url": "https://api.github.com/users/jadielam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielam/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielsonnsouza",
      "id": 50425637,
      "node_id": "MDQ6VXNlcjUwNDI1NjM3",
      "avatar_url": "https://avatars.githubusercontent.com/u/50425637?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielsonnsouza",
      "html_url": "https://github.com/jadielsonnsouza",
      "followers_url": "https://api.github.com/users/jadielsonnsouza/followers",
      "following_url": "https://api.github.com/users/jadielsonnsouza/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielsonnsouza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielsonnsouza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielsonnsouza/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielsonnsouza/orgs",
      "repos_url": "https://api.github.com/users/jadielsonnsouza/repos",
      "events_url": "https://api.github.com/users/jadielsonnsouza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielsonnsouza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielJr",
      "id": 39445244,
      "node_id": "MDQ6VXNlcjM5NDQ1MjQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/39445244?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielJr",
      "html_url": "https://github.com/JadielJr",
      "followers_url": "https://api.github.com/users/JadielJr/followers",
      "following_url": "https://api.github.com/users/JadielJr/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielJr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielJr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielJr/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielJr/orgs",
      "repos_url": "https://api.github.com/users/JadielJr/repos",
      "events_url": "https://api.github.com/users/JadielJr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielJr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadiellyL",
      "id": 20784224,
      "node_id": "MDQ6VXNlcjIwNzg0MjI0",
      "avatar_url": "https://avatars.githubusercontent.com/u/20784224?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadiellyL",
      "html_url": "https://github.com/JadiellyL",
      "followers_url": "https://api.github.com/users/JadiellyL/followers",
      "following_url": "https://api.github.com/users/JadiellyL/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadiellyL/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadiellyL/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadiellyL/subscriptions",
      "organizations_url": "https://api.github.com/users/JadiellyL/orgs",
      "repos_url": "https://api.github.com/users/JadiellyL/repos",
      "events_url": "https://api.github.com/users/JadiellyL/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadiellyL/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielmwangi",
      "id": 59909033,
      "node_id": "MDQ6VXNlcjU5OTA5MDMz",
      "avatar_url": "https://avatars.githubusercontent.com/u/59909033?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielmwangi",
      "html_url": "https://github.com/jadielmwangi",
      "followers_url": "https://api.github.com/users/jadielmwangi/followers",
      "following_url": "https://api.github.com/users/jadielmwangi/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielmwangi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielmwangi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielmwangi/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielmwangi/orgs",
      "repos_url": "https://api.github.com/users/jadielmwangi/repos",
      "events_url": "https://api.github.com/users/jadielmwangi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielmwangi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielTeofilo",
      "id": 12130155,
      "node_id": "MDQ6VXNlcjEyMTMwMTU1",
      "avatar_url": "https://avatars.githubusercontent.com/u/12130155?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielTeofilo",
      "html_url": "https://github.com/JadielTeofilo",
      "followers_url": "https://api.github.com/users/JadielTeofilo/followers",
      "following_url": "https://api.github.com/users/JadielTeofilo/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielTeofilo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielTeofilo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielTeofilo/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielTeofilo/orgs",
      "repos_url": "https://api.github.com/users/JadielTeofilo/repos",
      "events_url": "https://api.github.com/users/JadielTeofilo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielTeofilo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadielson-dev",
      "id": 69129052,
      "node_id": "MDQ6VXNlcjY5MTI5MDUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/69129052?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadielson-dev",
      "html_url": "https://github.com/Jadielson-dev",
      "followers_url": "https://api.github.com/users/Jadielson-dev/followers",
      "following_url": "https://api.github.com/users/Jadielson-dev/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadielson-dev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadielson-dev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadielson-dev/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadielson-dev/orgs",
      "repos_url": "https://api.github.com/users/Jadielson-dev/repos",
      "events_url": "https://api.github.com/users/Jadielson-dev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadielson-dev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielsonSantos",
      "id": 78828355,
      "node_id": "MDQ6VXNlcjc4ODI4MzU1",
      "avatar_url": "https://avatars.githubusercontent.com/u/78828355?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielsonSantos",
      "html_url": "https://github.com/JadielsonSantos",
      "followers_url": "https://api.github.com/users/JadielsonSantos/followers",
      "following_url": "https://api.github.com/users/JadielsonSantos/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielsonSantos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielsonSantos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielsonSantos/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielsonSantos/orgs",
      "repos_url": "https://api.github.com/users/JadielsonSantos/repos",
      "events_url": "https://api.github.com/users/JadielsonSantos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielsonSantos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadiel-Santana",
      "id": 48699769,
      "node_id": "MDQ6VXNlcjQ4Njk5NzY5",
      "avatar_url": "https://avatars.githubusercontent.com/u/48699769?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadiel-Santana",
      "html_url": "https://github.com/Jadiel-Santana",
      "followers_url": "https://api.github.com/users/Jadiel-Santana/followers",
      "following_url": "https://api.github.com/users/Jadiel-Santana/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadiel-Santana/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadiel-Santana/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadiel-Santana/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadiel-Santana/orgs",
      "repos_url": "https://api.github.com/users/Jadiel-Santana/repos",
      "events_url": "https://api.github.com/users/Jadiel-Santana/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadiel-Santana/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielsanttos",
      "id": 82414367,
      "node_id": "MDQ6VXNlcjgyNDE0MzY3",
      "avatar_url": "https://avatars.githubusercontent.com/u/82414367?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielsanttos",
      "html_url": "https://github.com/jadielsanttos",
      "followers_url": "https://api.github.com/users/jadielsanttos/followers",
      "following_url": "https://api.github.com/users/jadielsanttos/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielsanttos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielsanttos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielsanttos/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielsanttos/orgs",
      "repos_url": "https://api.github.com/users/jadielsanttos/repos",
      "events_url": "https://api.github.com/users/jadielsanttos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielsanttos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielSantos",
      "id": 38146469,
      "node_id": "MDQ6VXNlcjM4MTQ2NDY5",
      "avatar_url": "https://avatars.githubusercontent.com/u/38146469?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielSantos",
      "html_url": "https://github.com/JadielSantos",
      "followers_url": "https://api.github.com/users/JadielSantos/followers",
      "following_url": "https://api.github.com/users/JadielSantos/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielSantos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielSantos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielSantos/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielSantos/orgs",
      "repos_url": "https://api.github.com/users/JadielSantos/repos",
      "events_url": "https://api.github.com/users/JadielSantos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielSantos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielAbap",
      "id": 56039000,
      "node_id": "MDQ6VXNlcjU2MDM5MDAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/56039000?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielAbap",
      "html_url": "https://github.com/JadielAbap",
      "followers_url": "https://api.github.com/users/JadielAbap/followers",
      "following_url": "https://api.github.com/users/JadielAbap/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielAbap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielAbap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielAbap/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielAbap/orgs",
      "repos_url": "https://api.github.com/users/JadielAbap/repos",
      "events_url": "https://api.github.com/users/JadielAbap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielAbap/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielqt",
      "id": 19312008,
      "node_id": "MDQ6VXNlcjE5MzEyMDA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/19312008?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielqt",
      "html_url": "https://github.com/jadielqt",
      "followers_url": "https://api.github.com/users/jadielqt/followers",
      "following_url": "https://api.github.com/users/jadielqt/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielqt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielqt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielqt/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielqt/orgs",
      "repos_url": "https://api.github.com/users/jadielqt/repos",
      "events_url": "https://api.github.com/users/jadielqt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielqt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielMouchrek",
      "id": 53784014,
      "node_id": "MDQ6VXNlcjUzNzg0MDE0",
      "avatar_url": "https://avatars.githubusercontent.com/u/53784014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielMouchrek",
      "html_url": "https://github.com/JadielMouchrek",
      "followers_url": "https://api.github.com/users/JadielMouchrek/followers",
      "following_url": "https://api.github.com/users/JadielMouchrek/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielMouchrek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielMouchrek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielMouchrek/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielMouchrek/orgs",
      "repos_url": "https://api.github.com/users/JadielMouchrek/repos",
      "events_url": "https://api.github.com/users/JadielMouchrek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielMouchrek/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielpt",
      "id": 10165013,
      "node_id": "MDQ6VXNlcjEwMTY1MDEz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10165013?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielpt",
      "html_url": "https://github.com/jadielpt",
      "followers_url": "https://api.github.com/users/jadielpt/followers",
      "following_url": "https://api.github.com/users/jadielpt/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielpt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielpt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielpt/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielpt/orgs",
      "repos_url": "https://api.github.com/users/jadielpt/repos",
      "events_url": "https://api.github.com/users/jadielpt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielpt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jack11111",
      "id": 19857570,
      "node_id": "MDQ6VXNlcjE5ODU3NTcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/19857570?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jack11111",
      "html_url": "https://github.com/Jack11111",
      "followers_url": "https://api.github.com/users/Jack11111/followers",
      "following_url": "https://api.github.com/users/Jack11111/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jack11111/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jack11111/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jack11111/subscriptions",
      "organizations_url": "https://api.github.com/users/Jack11111/orgs",
      "repos_url": "https://api.github.com/users/Jack11111/repos",
      "events_url": "https://api.github.com/users/Jack11111/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jack11111/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielsousa",
      "id": 22748343,
      "node_id": "MDQ6VXNlcjIyNzQ4MzQz",
      "avatar_url": "https://avatars.githubusercontent.com/u/22748343?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielsousa",
      "html_url": "https://github.com/jadielsousa",
      "followers_url": "https://api.github.com/users/jadielsousa/followers",
      "following_url": "https://api.github.com/users/jadielsousa/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielsousa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielsousa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielsousa/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielsousa/orgs",
      "repos_url": "https://api.github.com/users/jadielsousa/repos",
      "events_url": "https://api.github.com/users/jadielsousa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielsousa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadielson-Santos",
      "id": 62728073,
      "node_id": "MDQ6VXNlcjYyNzI4MDcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/62728073?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadielson-Santos",
      "html_url": "https://github.com/Jadielson-Santos",
      "followers_url": "https://api.github.com/users/Jadielson-Santos/followers",
      "following_url": "https://api.github.com/users/Jadielson-Santos/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadielson-Santos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadielson-Santos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadielson-Santos/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadielson-Santos/orgs",
      "repos_url": "https://api.github.com/users/Jadielson-Santos/repos",
      "events_url": "https://api.github.com/users/Jadielson-Santos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadielson-Santos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadieleiro",
      "id": 19764342,
      "node_id": "MDQ6VXNlcjE5NzY0MzQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/19764342?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadieleiro",
      "html_url": "https://github.com/Jadieleiro",
      "followers_url": "https://api.github.com/users/Jadieleiro/followers",
      "following_url": "https://api.github.com/users/Jadieleiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadieleiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadieleiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadieleiro/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadieleiro/orgs",
      "repos_url": "https://api.github.com/users/Jadieleiro/repos",
      "events_url": "https://api.github.com/users/Jadieleiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadieleiro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielRodz",
      "id": 90779855,
      "node_id": "MDQ6VXNlcjkwNzc5ODU1",
      "avatar_url": "https://avatars.githubusercontent.com/u/90779855?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielRodz",
      "html_url": "https://github.com/JadielRodz",
      "followers_url": "https://api.github.com/users/JadielRodz/followers",
      "following_url": "https://api.github.com/users/JadielRodz/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielRodz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielRodz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielRodz/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielRodz/orgs",
      "repos_url": "https://api.github.com/users/JadielRodz/repos",
      "events_url": "https://api.github.com/users/JadielRodz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielRodz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielbett",
      "id": 51707273,
      "node_id": "MDQ6VXNlcjUxNzA3Mjcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/51707273?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielbett",
      "html_url": "https://github.com/jadielbett",
      "followers_url": "https://api.github.com/users/jadielbett/followers",
      "following_url": "https://api.github.com/users/jadielbett/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielbett/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielbett/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielbett/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielbett/orgs",
      "repos_url": "https://api.github.com/users/jadielbett/repos",
      "events_url": "https://api.github.com/users/jadielbett/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielbett/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadieleiro1",
      "id": 19810596,
      "node_id": "MDQ6VXNlcjE5ODEwNTk2",
      "avatar_url": "https://avatars.githubusercontent.com/u/19810596?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadieleiro1",
      "html_url": "https://github.com/Jadieleiro1",
      "followers_url": "https://api.github.com/users/Jadieleiro1/followers",
      "following_url": "https://api.github.com/users/Jadieleiro1/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadieleiro1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadieleiro1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadieleiro1/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadieleiro1/orgs",
      "repos_url": "https://api.github.com/users/Jadieleiro1/repos",
      "events_url": "https://api.github.com/users/Jadieleiro1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadieleiro1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadieloseias-Sama",
      "id": 50417363,
      "node_id": "MDQ6VXNlcjUwNDE3MzYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/50417363?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadieloseias-Sama",
      "html_url": "https://github.com/jadieloseias-Sama",
      "followers_url": "https://api.github.com/users/jadieloseias-Sama/followers",
      "following_url": "https://api.github.com/users/jadieloseias-Sama/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadieloseias-Sama/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadieloseias-Sama/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadieloseias-Sama/subscriptions",
      "organizations_url": "https://api.github.com/users/jadieloseias-Sama/orgs",
      "repos_url": "https://api.github.com/users/jadieloseias-Sama/repos",
      "events_url": "https://api.github.com/users/jadieloseias-Sama/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadieloseias-Sama/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadiel1234gamer",
      "id": 93847149,
      "node_id": "U_kgDOBZf-bQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/93847149?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadiel1234gamer",
      "html_url": "https://github.com/jadiel1234gamer",
      "followers_url": "https://api.github.com/users/jadiel1234gamer/followers",
      "following_url": "https://api.github.com/users/jadiel1234gamer/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadiel1234gamer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadiel1234gamer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadiel1234gamer/subscriptions",
      "organizations_url": "https://api.github.com/users/jadiel1234gamer/orgs",
      "repos_url": "https://api.github.com/users/jadiel1234gamer/repos",
      "events_url": "https://api.github.com/users/jadiel1234gamer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadiel1234gamer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadiel007",
      "id": 84156955,
      "node_id": "MDQ6VXNlcjg0MTU2OTU1",
      "avatar_url": "https://avatars.githubusercontent.com/u/84156955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadiel007",
      "html_url": "https://github.com/Jadiel007",
      "followers_url": "https://api.github.com/users/Jadiel007/followers",
      "following_url": "https://api.github.com/users/Jadiel007/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadiel007/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadiel007/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadiel007/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadiel007/orgs",
      "repos_url": "https://api.github.com/users/Jadiel007/repos",
      "events_url": "https://api.github.com/users/Jadiel007/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadiel007/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadiellyLima",
      "id": 15957902,
      "node_id": "MDQ6VXNlcjE1OTU3OTAy",
      "avatar_url": "https://avatars.githubusercontent.com/u/15957902?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadiellyLima",
      "html_url": "https://github.com/JadiellyLima",
      "followers_url": "https://api.github.com/users/JadiellyLima/followers",
      "following_url": "https://api.github.com/users/JadiellyLima/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadiellyLima/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadiellyLima/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadiellyLima/subscriptions",
      "organizations_url": "https://api.github.com/users/JadiellyLima/orgs",
      "repos_url": "https://api.github.com/users/JadiellyLima/repos",
      "events_url": "https://api.github.com/users/JadiellyLima/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadiellyLima/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JadielGW",
      "id": 58263310,
      "node_id": "MDQ6VXNlcjU4MjYzMzEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/58263310?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JadielGW",
      "html_url": "https://github.com/JadielGW",
      "followers_url": "https://api.github.com/users/JadielGW/followers",
      "following_url": "https://api.github.com/users/JadielGW/following{/other_user}",
      "gists_url": "https://api.github.com/users/JadielGW/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JadielGW/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JadielGW/subscriptions",
      "organizations_url": "https://api.github.com/users/JadielGW/orgs",
      "repos_url": "https://api.github.com/users/JadielGW/repos",
      "events_url": "https://api.github.com/users/JadielGW/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JadielGW/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jadiele-08",
      "id": 59869432,
      "node_id": "MDQ6VXNlcjU5ODY5NDMy",
      "avatar_url": "https://avatars.githubusercontent.com/u/59869432?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jadiele-08",
      "html_url": "https://github.com/Jadiele-08",
      "followers_url": "https://api.github.com/users/Jadiele-08/followers",
      "following_url": "https://api.github.com/users/Jadiele-08/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jadiele-08/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jadiele-08/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jadiele-08/subscriptions",
      "organizations_url": "https://api.github.com/users/Jadiele-08/orgs",
      "repos_url": "https://api.github.com/users/Jadiele-08/repos",
      "events_url": "https://api.github.com/users/Jadiele-08/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jadiele-08/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jadielquispe",
      "id": 23409883,
      "node_id": "MDQ6VXNlcjIzNDA5ODgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/23409883?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jadielquispe",
      "html_url": "https://github.com/jadielquispe",
      "followers_url": "https://api.github.com/users/jadielquispe/followers",
      "following_url": "https://api.github.com/users/jadielquispe/following{/other_user}",
      "gists_url": "https://api.github.com/users/jadielquispe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jadielquispe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jadielquispe/subscriptions",
      "organizations_url": "https://api.github.com/users/jadielquispe/orgs",
      "repos_url": "https://api.github.com/users/jadielquispe/repos",
      "events_url": "https://api.github.com/users/jadielquispe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jadielquispe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}""";